# Generated by Django 4.0.4 on 2022-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagegallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_title', models.CharField(max_length=100)),
                ('Gallery_Image', models.ImageField(null=True, upload_to='gallery/')),
            ],
        ),
    ]
