# Generated by Django 4.0.4 on 2022-06-04 10:56

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('ProductDate',))),
                ('Price', models.IntegerField()),
                ('Des', models.TextField(max_length=100000000000000)),
                ('Date', models.DateTimeField()),
                ('PImage', models.ImageField(null=True, upload_to='productimg/')),
            ],
        ),
    ]
