# Generated by Django 4.0.4 on 2022-06-04 11:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['Name', 'Des', 'Price']),
        ),
    ]
