# Generated by Django 4.0.4 on 2022-06-04 11:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_tags_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['Name', 'Des', 'Tags']),
        ),
    ]
