# Generated by Django 4.0.4 on 2022-06-04 12:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='Des', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tags',
            field=models.CharField(choices=[('MF', 'Mens Fashion'), ('WF', 'Womens Fashion'), ('OF', 'Old Fashion'), ('KF', 'Kids Fashion'), ('FC', 'Fancy Collections')], max_length=100, null=True),
        ),
    ]
