# Generated by Django 4.0.4 on 2022-06-03 05:07

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Post_Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('Content', ckeditor.fields.RichTextField()),
                ('Header_Image', models.ImageField(null=True, upload_to='HeaderImage/')),
                ('Created_at', models.DateTimeField()),
            ],
        ),
    ]
