# Generated by Django 4.0.4 on 2022-06-03 05:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_Slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='Title', unique=True),
        ),
    ]
