# Generated by Django 4.0.4 on 2022-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=100)),
                ('Your_Email', models.EmailField(max_length=100)),
                ('Your_PH', models.IntegerField()),
                ('Your_Address', models.CharField(max_length=500)),
                ('Your_JobRole', models.CharField(max_length=100)),
                ('Your_Website', models.CharField(max_length=100)),
            ],
        ),
    ]
