# Generated by Django 4.0.4 on 2022-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_knowme'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowme',
            name='Your_FB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowme',
            name='Your_GITHUB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowme',
            name='Your_INSTA',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowme',
            name='Your_TW',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
